openapi: 3.0.0
info:
  title: Student Management API
  version: 1.1.0
  description: API for managing students, courses, and classes in a school.

servers:
  - url: http://localhost:3000
    description: Express server

paths:
  /students:
    post:
      summary: Add new students
      description: Add new students with basic information.
      tags:
        - Student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "201":
          description: Successfully created

    get:
      summary: Retrieve the list of students
      description: View the list of students or search based on criteria such as class or age.
      tags:
        - Student
      responses:
        "200":
          description: Successfully retrieved

  /students/{id}:
    get:
      summary: Retrieve a student
      description: View the details of a student.
      tags:
        - Student
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identification of the student
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: Successfully retrieved
        "404":
          description: Student not found

    delete:
      summary: Delete a student
      description: Delete a student from the system.
      tags:
        - Student
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identification of the student
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "204":
          description: Successfully deleted
        "404":
          description: Student not found

  /courses:
    post:
      summary: Add new courses
      description: Add new courses with basic information.
      tags:
        - Course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Course"
      responses:
        "201":
          description: Successfully created

    get:
      summary: Retrieve the list of courses
      description: View the list of courses or search based on criteria such as credits or name.
      tags:
        - Course
      responses:
        "200":
          description: Successfully retrieved

  /courses/{id}:
    get:
      summary: Retrieve a course
      description: View the details of a course.
      tags:
        - Course
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identification of the course
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: Successfully retrieved
        "404":
          description: Course not found

    delete:
      summary: Delete a course
      description: Delete a course from the system.
      tags:
        - Course
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identification of the course
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "204":
          description: Successfully deleted
        "404":
          description: Course not found

  /enroll:
    post:
      summary: Enroll a student in a course
      description: Enroll a student in a course.
      tags:
        - Enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: integer
                  format: int64
                  example: 1
                  description: Unique identification of the student
                courseId:
                  type: integer
                  format: int64
                  example: 1
                  description: Unique identification of the course
      responses:
        "201":
          description: Successfully enrolled
        "404":
          description: Student or course not found

    delete:
      summary: Withdraw a student from a course
      description: Withdraw a student from a course.
      tags:
        - Enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: integer
                  format: int64
                  example: 1
                  description: Unique identification of the student
      responses:
        "204":
          description: Successfully unenrolled
        "404":
          description: Student or course not found

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          example: 1
          format: int64
          description: Unique identification of the student
        name:
          type: string
          example: John Doe
          description: Name of the student
        age:
          type: integer
          format: int32
          example: 25
          description: Age of the student
        email:
          type: string
          format: email
          example: "john.doe@example.com"
          description: Email address of the student
        phone:
          type: string
          example: "123-456-7890"
          description: Phone number of the student
        courseId:
          type: integer
          format: int64
          example: 1
          description: Unique identification of the course

    Course:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: Unique identification of the course
        name:
          type: string
          example: Mathematics
          description: Name of the course
        description:
          type: string
          example: "Introduction to Algebra"
          description: Description of the course
        credits:
          type: integer
          format: int32
          example: 3
          description: Number of credits for the course
