openapi: 3.0.0
info:
  title: Student Management API
  version: 1.1.0
  description: API for managing students, courses, and classes in a school.

paths:
  /students:
    post:
      summary: Add new students
      description: Add new students with basic information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "201":
          description: Successfully created

    get:
      summary: Retrieve the list of students
      description: View the list of students or search based on criteria such as class or age.
      responses:
        "200":
          description: Successfully retrieved

  /students/{studentId}:
    put:
      summary: Update student information
      description: Update student information when changes occur.
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student to be updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          description: Successfully updated

    delete:
      summary: Delete students
      description: Delete students who have left the school.
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student to be deleted
          schema:
            type: string
      responses:
        "204":
          description: Successfully deleted

  /students/{studentId}/enrollments:
    post:
      summary: Enroll in a course
      description: Enroll a student in a course.
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student to enroll
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Course"
      responses:
        "201":
          description: Successfully enrolled

  /students/{studentId}/enrollments/{courseId}:
    delete:
      summary: Withdraw from a course
      description: Withdraw a student from a course.
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student to withdraw
          schema:
            type: string
        - name: courseId
          in: path
          required: true
          description: ID of the course to withdraw from
          schema:
            type: string
      responses:
        "204":
          description: Successfully withdrawn

  /students/{studentId}/courses:
    get:
      summary: Retrieve the list of courses
      description: View the list of courses that a student is enrolled in.
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student to view courses
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved

  /courses/{courseId}/classes:
    get:
      summary: Retrieve the list of classes
      description: View the list of classes for a course.
      parameters:
        - name: courseId
          in: path
          required: true
          description: ID of the course to view classes
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identification of the student
        firstname:
          type: string
          description: First name of the student
        lastname:
          type: string
          description: Last name of the student
        email:
          type: string
          format: email
          description: Email address of the student
        course:
          $ref: "#/components/schemas/Course"
        classes:
          type: array
          items:
            $ref: "#/components/schemas/Class"

    Course:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identification of the course
        name:
          type: string
          description: Name of the course

    Class:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identification of the class
        name:
          type: string
          description: Name of the class
